package com.iv.gravity.constants;

import java.util.Set;
import com.google.common.collect.ImmutableSet;

public class GravityTables {

   // Table
   public static final String GRAVITY_MAIN_TABLE = "iv_gravity_story_codereview";

   // Columns
   public static final String COLUMN_STORYID = "iv_gravity_story_id"; // Postgresql Datatype - text

   public static final String COLUMN_USERNAME = "iv_gravity_username"; // Postgresql Datatype - text

   public static final String COLUMN_STORY_TYPE = "iv_gravity_story_type"; // Postgresql Datatype - text

   public static final String COLUMN_TIMEANALYZED = "iv_gravity_time_analyzed"; // Postgresql Datatype - timestamp(with
   // timezone)

   public static final String COLUMN_REPOSITORY = "iv_gravity_repository"; // Postgresql Datatype - text

   public static final String COLUMN_BRANCH = "iv_gravity_branch"; // Postgresql Datatype - text

   public static final String COLUMN_LICENSE_GROUP = "iv_gravity_license_group"; // Postgresql Datatype - text

   public static final String COLUMN_LICENSE = "iv_gravity_license"; // Postgresql Datatype - text

   public static final String COLUMN_SUBSYSTEM = "iv_gravity_subsystem"; // Postgresql Datatype - text

   public static final String COLUMN_EPIC = "iv_gravity_epic"; // Postgresql Datatype - text

   public static final String COLUMN_TOTAL_BUGS = "iv_gravity_total_bugs"; // Postgresql Datatype - integer

   public static final String COLUMN_CRITICAL_BUGS = "iv_gravity_critical_bugs"; // Postgresql Datatype - integer

   public static final String COLUMN_MAJOR_BUGS = "iv_gravity_major_bugs"; // Postgresql Datatype - integer

   public static final String COLUMN_MINOR_BUGS = "iv_gravity_minor_bugs"; // Postgresql Datatype - integer

   public static final String COLUMN_ANALYSER_IP = "iv_gravity_analyser_ip"; // Postgresql Datatype - inet

   public static final String COLUMN_ADDITIONAL_DATA_STORY = "iv_gravity_additional_data"; // Postgresql Datatype -
   // json

   public static final Set<String> GRAVITY_MAIN_TABLE_COLUMNS = ImmutableSet.of(COLUMN_STORYID, COLUMN_USERNAME, COLUMN_STORY_TYPE,
      COLUMN_TIMEANALYZED, COLUMN_REPOSITORY, COLUMN_BRANCH, COLUMN_LICENSE_GROUP, COLUMN_LICENSE, COLUMN_SUBSYSTEM, COLUMN_EPIC, COLUMN_TOTAL_BUGS,
      COLUMN_CRITICAL_BUGS, COLUMN_MAJOR_BUGS, COLUMN_MINOR_BUGS, COLUMN_ANALYSER_IP, COLUMN_ADDITIONAL_DATA_STORY);

   // Table
   public static final String GRAVITY_FILE_REPORT_TABLE = "iv_gravity_file_report";

   // Columns
   public static final String COLUMN_FILE_NAME = "iv_gravity_file_name"; // Postgresql Datatype - text

   public static final String COLUMN_FILE_TYPE = "iv_gravity_file_type"; // Postgresql Datatype - text

   public static final String COLUMN_REPOSITORY_FILE = "iv_gravity_repository"; // Postgresql Datatype - text

   public static final String COLUMN_BRANCH_FILE = "iv_gravity_branch"; // Postgresql Datatype - text

   public static final String COLUMN_LICENSE_GROUP_FILE = "iv_gravity_license_group"; // Postgresql Datatype - text

   public static final String COLUMN_LICENSE_FILE = "iv_gravity_license"; // Postgresql Datatype - text

   public static final String COLUMN_SUBSYSTEM_FILE = "iv_gravity_subsystem"; // Postgresql Datatype - text

   public static final String COLUMN_EPIC_FILE = "iv_gravity_epic"; // Postgresql Datatype - text

   public static final String COLUMN_REMOTE_PATH = "iv_gravity_remote_path"; // Postgresql Datatype - text

   public static final String COLUMN_AUTHOR_OF_FILE = "iv_gravity_author_of_file"; // Postgresql Datatype - text

   public static final String COLUMN_NUMBER_OF_LINES = "iv_gravity_number_of_lines"; // Postgresql Datatype - integer

   public static final String COLUMN_IS_AUTOGENERATED = "iv_gravity_is_autogenerated"; // Postgresql Datatype - boolean

   public static final String COLUMN_TOTAL_BUGS_FILE = "iv_gravity_total_bugs"; // Postgresql Datatype - integer

   public static final String COLUMN_CRITICAL_BUGS_FILE = "iv_gravity_critical_bugs"; // Postgresql Datatype - integer

   public static final String COLUMN_MAJOR_BUGS_FILE = "iv_gravity_major_bugs"; // Postgresql Datatype - integer

   public static final String COLUMN_MINOR_BUGS_FILE = "iv_gravity_minor_bugs"; // Postgresql Datatype - integer

   public static final String COLUMN_BLAME_DETAILS = "iv_gravity_blame_details"; // Postgresql Datatype - jsonb

   public static final String FOREIGN_COLUMN_STORY_ID = "iv_gravity_story_id"; // Postgresql Datatype - text

   public static final String FOREIGN_COLUMN_USER_ANALYZED = "iv_gravity_user_analysed"; // Postgresql Datatype - text

   public static final String COLUMN_BUG_DETAILS = "iv_gravity_bug_details"; // Postgresql Datatype - jsonb

   public static final String COLUMN_FILE_CONTENTS = "iv_gravity_file_contents"; // Postgresql Datatype - bytea

   public static final String COLUMN_ADDITIONAL_DATA_FILE = "iv_gravity_additional_data"; // Postgresql Datatype - json

   public static final Set<String> GRAVITY_FILE_REPORT_TABLE_COLUMNS = ImmutableSet.of(COLUMN_FILE_NAME, COLUMN_FILE_TYPE, COLUMN_REPOSITORY_FILE,
      COLUMN_BRANCH_FILE, COLUMN_LICENSE_GROUP_FILE, COLUMN_LICENSE_FILE, COLUMN_SUBSYSTEM_FILE, COLUMN_EPIC_FILE, COLUMN_REMOTE_PATH,
      COLUMN_AUTHOR_OF_FILE, COLUMN_NUMBER_OF_LINES, COLUMN_IS_AUTOGENERATED, COLUMN_TOTAL_BUGS_FILE, COLUMN_CRITICAL_BUGS_FILE,
      COLUMN_MAJOR_BUGS_FILE, COLUMN_MINOR_BUGS_FILE, COLUMN_BLAME_DETAILS, FOREIGN_COLUMN_STORY_ID, FOREIGN_COLUMN_USER_ANALYZED, COLUMN_BUG_DETAILS,
      COLUMN_FILE_CONTENTS, COLUMN_ADDITIONAL_DATA_FILE);

   // Table
   public static final String GRAVITY_HISTORY_TABLE = "iv_gravity_story_bughistory";

   public static final String COLUMN_FILES_REPORT_HISTORY = "iv_gravity_files_report"; // Postgresql Datatype - jsonb

   public static final Set<String> GRAVITY_HISTORY_TABLE_COLUMNS = ImmutableSet.of(COLUMN_STORYID, COLUMN_USERNAME, COLUMN_STORY_TYPE,
      COLUMN_TIMEANALYZED, COLUMN_REPOSITORY, COLUMN_BRANCH, COLUMN_LICENSE_GROUP, COLUMN_LICENSE, COLUMN_SUBSYSTEM, COLUMN_EPIC, COLUMN_TOTAL_BUGS,
      COLUMN_CRITICAL_BUGS, COLUMN_MAJOR_BUGS, COLUMN_MINOR_BUGS, COLUMN_ANALYSER_IP, COLUMN_ADDITIONAL_DATA_STORY, COLUMN_FILES_REPORT_HISTORY);

   // Table
   public static final String GRAVITY_STORE_BUGFIX_TABLE = "iv_gravity_story_bugfixedfiles";

   public static final String COLUMN_BUG_FIXED_FILES = "iv_gravity_bug_fixed_files";

   public static final Set<String> GRAVITY_STORE_BUGFIX_TABLE_COLUMNS = ImmutableSet.of(COLUMN_STORYID, COLUMN_STORY_TYPE, COLUMN_REPOSITORY,
      COLUMN_BRANCH, COLUMN_LICENSE_GROUP, COLUMN_LICENSE, COLUMN_SUBSYSTEM, COLUMN_EPIC, COLUMN_BUG_FIXED_FILES, COLUMN_TIMEANALYZED,
      COLUMN_USERNAME);

   // Table
   // public static final String CORTEX_STORY_DETAILS_TABLE_NAME = "ctx_story_details";

   // Table
   // public static final String ISSUE_LIST_TABLE_NAME = "time_entries_tbl";

   // public static final String COLUMN_USERID="user_id";

   // Table
   // public static final String STORIES_FROM_GREENEYE_TABLE_NAME = " issue_creation_tbl";

   // public static final String COLUMN_ISSUE_ID = "issue_id";

   // public static final String COLUMN_STORY_ID="root_id";

   // Table
   public static final String GREENEYE_ISSUE_TABLE = "issue";

   // Columns
   public static final String COLUMN_ASSIGNEE = "assignee";

   public static final String COLUMN_ROOTID = "root_id";

   public static final String COLUMN_INCHARGE_INPUT02 = "incharge_input02";

   // Table
   public static final String CORTEX_STORY_INFO = "ctx_story_info";

   // Columns
   public static final String COLUMN_CTX_STORY_ID = "story_id";

   public static final String COLUMN_CTX_STORY_NAME = "epic_name";

   public static final String COLUMN_CTX_STORY_STATUS = "status";

   public static final String COLUMN_CTX_STORY_FOLDER_PATH = "folder_path";

   public static final String COLUMN_CTX_STORY_LAUNCH_VERSION = "launch_version";

   public static final String COLUMN_CTX_STORY_WORKING_BRANCH = "branch_name";

   // Table
   public static final String CORTEX_REPO_INFO = "ctx_repo_info";

   // Columns
   public static final String COLUMN_CTX_REPO_ID = "id";

   public static final String COLUMN_CTX_REPO_IDTYPE = "id_type";

   public static final String COLUMN_CTX_REPO_TYPE = "type";

   public static final String COLUMN_CTX_REPO_NAME = "repo_name";

   // Table
   public static final String CORTEX_PROJECT_INFO = "ctx_project_info";

   // Columns
   public static final String COLUMN_CORTEX_PROJECT_INFO_PROJECTNAME = "project_name";

   public static final String COLUMN_CORTEX_PROJECT_INFO_GITURL = "git_url";

}
